#!/usr/bin/env ruby

require 'artoo'

connection :keyboard, adaptor: :keyboard, port: '/dev/ttyS4'
device :keyboard, driver: :keyboard, connection: :keyboard

work do
  on keyboard, :key => :keypress
end

def keypress(sender, key)
  puts key
end

class CommandParser
end
